config/routes.rb
Rails.application.routes.draw do
  root "welcome#show"

  resource :first_run

  resource :session do
    scope module: "sessions" do
      resources :transfers, only: %i[ show update ]
    end
  end

  resource :account do
    scope module: "accounts" do
      resources :users
      resource :join_code, only: :create
      resource :logo, only: %i[ show destroy ]
    end
  end

  direct :fresh_account_logo do |options|
    route_for :account_logo, v: Current.account&.updated_at&.to_fs(:number)
  end

  get "join/:join_code", to: "users#new", as: :join
  post "join/:join_code", to: "users#create"

  resources :qr_code, only: :show

  resources :users, only: :show do
    scope module: "users" do
      resource :avatar, only: %i[ show destroy ]

      scope defaults: { user_id: "me" } do
        resource :sidebar, only: :show
        resource :profile
        resources :push_subscriptions do
          scope module: "push_subscriptions" do
            resources :test_notifications, only: :create
          end
        end
      end
    end
  end

  namespace :autocompletable do
    resources :users, only: :index
  end

  direct :fresh_user_avatar do |user, options|
    route_for :user_avatar, user, v: user.updated_at.to_fs(:number)
  end

  resources :rooms do
    resources :messages

    scope module: "rooms" do
      resource :refresh, only: :show
      resource :settings, only: :show
      resource :involvement, only: %i[ show update ]
    end

    get "@:message_id", to: "rooms#show", as: :at_message
  end

  namespace :rooms do
    resources :opens
    resources :closeds
    resources :directs
  end

  resources :messages do
    scope module: "messages" do
      resources :boosts
    end
  end

  resources :searches, only: %i[ index create ] do
    delete :clear, on: :collection
  end

  resource :unfurl_link, only: :create

  get "webmanifest"    => "pwa#manifest"
  get "service-worker" => "pwa#service_worker"

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/user.rb
class User < ApplicationRecord
  include Mentionable, Role, Transferable

  has_many :memberships, dependent: :delete_all
  has_many :rooms, through: :memberships

  has_many :reachable_messages, through: :rooms, source: :messages
  has_many :messages, dependent: :destroy, foreign_key: :creator_id

  has_many :push_subscriptions, class_name: "Push::Subscription", dependent: :delete_all

  has_many :boosts, dependent: :destroy, foreign_key: :booster_id
  has_many :searches, dependent: :delete_all

  has_many :sessions, dependent: :destroy

  scope :active, -> { where(active: true) }

  has_one_attached :avatar
  has_secure_password validations: false

  after_create_commit :grant_membership_to_open_rooms

  scope :ordered, -> { order("LOWER(name)") }
  scope :filtered_by, ->(query) { where("name like ?", "%#{query}%") }

  def initials
    name.scan(/\b\w/).join
  end

  def title
    [ name, bio ].compact_blank.join(" – ")
  end

  def deactivate
    transaction do
      close_remote_connections

      memberships.without_direct_rooms.delete_all
      push_subscriptions.delete_all
      searches.delete_all
      sessions.delete_all

      update! active: false, email_address: deactived_email_address
    end
  end

  def deactivated?
    !active?
  end

  private
    def grant_membership_to_open_rooms
      Rooms::Open.find_each { |room| room.memberships.grant_to self }
    end

    def deactived_email_address
      email_address.gsub(/@/, "-deactivated-#{SecureRandom.uuid}@")
    end

    def close_remote_connections
      ActionCable.server.remote_connections.where(current_user: self).disconnect reconnect: false
    end
end

app/models/user/mentionable.rb
module User::Mentionable
  include ActionText::Attachable

  def to_attachable_partial_path
    "users/mention"
  end

  def to_trix_content_attachment_partial_path
    "users/mention"
  end

  def attachable_plain_text_representation(caption)
    "@#{name}"
  end
end

app/models/user/role.rb
module User::Role
  extend ActiveSupport::Concern

  included do
    enum role: %i[ member administrator ]
  end

  def can_administer?(record = nil)
    administrator? || self == record&.creator || record&.new_record?
  end
end

app/models/user/transferable.rb
module User::Transferable
  extend ActiveSupport::Concern

  TRANSFER_LINK_EXPIRY_DURATION = 4.hours

  class_methods do
    def find_by_transfer_id(id)
      find_signed(id, purpose: :transfer)
    end
  end

  def transfer_id
    signed_id(purpose: :transfer, expires_in: TRANSFER_LINK_EXPIRY_DURATION)
  end
end

app/controllers/accounts/users_controller.rb
class Accounts::UsersController < ApplicationController
  before_action :ensure_can_administer, :set_user, only: %i[ update destroy ]

  def index
    set_page_and_extract_portion_from User.active.ordered, per_page: 500
  end

  def update
    @user.update(role_params)
    redirect_to edit_account_url
  end

  def destroy
    @user.deactivate
    redirect_to edit_account_url
  end

  private
    def set_user
      @user = User.active.find(params[:user_id] || params[:id])
    end

    def role_params
      { role: params.require(:user)[:role].presence_in(%w[ member administrator ]) || "member" }
    end
end

app/controllers/autocompletable/users_controller.rb
class Autocompletable::UsersController < ApplicationController
  def index
    set_page_and_extract_portion_from find_autocompletable_users.with_attached_avatar.ordered, per_page: 20
  end

  private
    def find_autocompletable_users
      params[:query].present? ? users_scope.active.filtered_by(params[:query]) : users_scope.active
    end

    def users_scope
      params[:room_id].present? ? Room.find(params[:room_id]).users : User.all
    end
end

app/controllers/users/avatars_controller.rb
class Users::AvatarsController < ApplicationController
  include ActiveStorage::Streaming

  def show
    @user = User.find(params[:user_id])

    if stale?(etag: @user)
      expires_in 30.minutes, public: true, stale_while_revalidate: 1.week

      if @user.avatar.attached?
        avatar_variant = @user.avatar.variant(SQUARE_WEBP_VARIANT).processed
        send_webp_blob_file avatar_variant.key
      else
        render_initials
      end
    end
  end

  def destroy
    Current.user.avatar.destroy
    redirect_to user_profile_url
  end

  private
    SQUARE_WEBP_VARIANT = { resize_to_limit: [ 512, 512 ], format: :webp }

    def send_webp_blob_file(key)
      send_file ActiveStorage::Blob.service.path_for(key), content_type: "image/webp", disposition: :inline
    end

    def render_initials
      render formats: :svg
    end
end

app/controllers/users/profiles_controller.rb
class Users::ProfilesController < ApplicationController
  before_action :set_user

  def show
    @direct_memberships, @shared_memberships =
      Current.user.memberships.with_ordered_room.partition { |m| m.room.direct? }
  end

  def update
    @user.update user_params
    redirect_to user_profile_url, notice: update_notice
  end

  private
    def set_user
      @user = Current.user
    end

    def user_params
      params.require(:user).permit(:name, :avatar, :email_address, :password, :bio).compact
    end

    def update_notice
      params[:user][:avatar] ? "It may take up to 30 minutes to change everywhere." : "✓"
    end
end

app/controllers/users/push_subscriptions/test_notifications_controller.rb
class Users::PushSubscriptions::TestNotificationsController < ApplicationController
  before_action :set_push_subscription

  def create
    @push_subscription.notification(title: "Campfire Test", body: Random.uuid, path: user_push_subscriptions_url).deliver
    redirect_to user_push_subscriptions_url
  end

  private
    def set_push_subscription
      @push_subscription = Current.user.push_subscriptions.find(params[:push_subscription_id])
    end
end

app/controllers/users/push_subscriptions_controller.rb
class Users::PushSubscriptionsController < ApplicationController
  before_action :set_push_subscriptions

  def index
  end

  def create
    if subscription = @push_subscriptions.find_by(push_subscription_params)
      subscription.touch
    else
      @push_subscriptions.create! push_subscription_params.merge(user_agent: request.user_agent)
    end

    head :ok
  end

  def destroy
    @push_subscriptions.destroy_by(id: params[:id])
    redirect_to user_push_subscriptions_url
  end

  private
    def set_push_subscriptions
      @push_subscriptions = Current.user.push_subscriptions
    end

    def push_subscription_params
      params.require(:push_subscription).permit(:endpoint, :p256dh_key, :auth_key)
    end
end

app/controllers/users/sidebars_controller.rb
class Users::SidebarsController < ApplicationController
  DIRECT_PLACEHOLDERS = 20

  def show
    all_memberships     = Current.user.memberships.visible.with_ordered_room
    @direct_memberships = extract_direct_memberships(all_memberships)
    @other_memberships  = all_memberships.without(@direct_memberships)

    @direct_placeholder_users = find_direct_placeholder_users
  end

  private
    def extract_direct_memberships(all_memberships)
      all_memberships.select { |m| m.room.direct? }.sort_by { |m| m.room.updated_at }.reverse
    end

    def find_direct_placeholder_users
      exclude_user_ids = user_ids_already_in_direct_rooms_with_current_user.including(Current.user.id)
      User.active.where.not(id: exclude_user_ids).order(:created_at).limit(DIRECT_PLACEHOLDERS - exclude_user_ids.count)
    end

    def user_ids_already_in_direct_rooms_with_current_user
      Membership.where(room_id: Current.user.rooms.directs.pluck(:id)).pluck(:user_id).uniq
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  require_unauthenticated_access only: %i[ new create ]

  before_action :set_user, only: :show
  before_action :verify_join_code, only: %i[ new create ]

  def new
    @user = User.new
  end

  def create
    @user = User.create!(user_params)
    start_new_session_for @user
    redirect_to root_url
  rescue ActiveRecord::RecordNotUnique
    redirect_to new_session_url(email_address: user_params[:email_address])
  end

  def show
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def verify_join_code
      head :not_found if Current.account.join_code != params[:join_code]
    end

    def user_params
      params.require(:user).permit(:name, :avatar, :email_address, :password)
    end
end

app/helpers/users/avatars_helper.rb
require "zlib"

module Users::AvatarsHelper
  AVATAR_COLORS = %w[
    #AF2E1B #CC6324 #3B4B59 #BFA07A #ED8008 #ED3F1C #BF1B1B #736B1E #D07B53
    #736356 #AD1D1D #BF7C2A #C09C6F #698F9C #7C956B #5D618F #3B3633 #67695E
  ]

  def avatar_background_color(user)
    AVATAR_COLORS[Zlib.crc32(user.to_param) % AVATAR_COLORS.size]
  end

  def avatar_tag(user, **options)
    link_to user_path(user), title: user.title, class: "btn avatar", data: { turbo_frame: "_top" } do
      image_tag fresh_user_avatar_path(user), role: "presentation", **options
    end
  end
end

app/helpers/users/filter_helper.rb
module Users::FilterHelper
  def user_filter_menu_tag(&)
    tag.menu class: "flex flex-column gap margin-none pad overflow-y constrain-height",
      data: { controller: "filter", filter_active_class: "filter--active", filter_selected_class: "selected" }, &
  end

  def user_filter_search_tag
    tag.input type: "search", id: "search", autocorrect: "off", autocomplete: "off", "data-1p-ignore": "true", class: "input input--transparent full-width", placeholder: "Filter…", data: { action: "input->filter#filter" }
  end
end

app/helpers/users/profiles_helper.rb
module Users::ProfilesHelper
  def profile_form_with(model, **params, &)
    form_with \
      model: @user, url: user_profile_path, method: :patch,
      data: { controller: "form", action: "keydown.enter->form#submit:prevent" },
      **params,
      &
  end

  def profile_form_submit_button
    tag.button class: "btn btn--reversed center txt-large", type: "submit" do
      image_tag("check.svg") +
      tag.span("Save changes", class: "for-screen-reader")
    end
  end

  def web_share_session_button(url, title, text, &)
    tag.button class: "btn", hidden: true, data: {
      controller: "web-share", action: "web-share#share",
      web_share_url_value: url,
      web_share_text_value: text,
      web_share_title_value: title
    }, &
  end
end

app/helpers/users/sidebar_helper.rb
module Users::SidebarHelper
  def sidebar_turbo_frame_tag(src: nil, &)
    turbo_frame_tag :user_sidebar, src: src, target: "_top", data: {
      turbo_permanent: true,
      controller: "rooms-list read-rooms turbo-frame",
      rooms_list_unread_class: "unread",
      action: "presence:present@window->rooms-list#read read-rooms:read->rooms-list#read turbo:frame-load->rooms-list#loaded refresh-room:visible@window->turbo-frame#reload".html_safe # otherwise -> is escaped
    }, &
  end
end

app/views/users/profiles/_membership.html.erb
<li class="flex align-center gap margin-none min-width membership-item">
  <%= link_to room_path(membership.room), class: "overflow-ellipsis fill-shade txt-primary txt-undecorated" do %>
    <strong><%= room_display_name(membership.room) %></strong>
  <% end %>

  <hr class="separator">

  <span class="txt-small">
    <%= turbo_frame_tag dom_id(membership.room, :involvement) do %>
      <%= button_to_change_involvement(membership.room, membership.involvement) %>
    <% end %>
  </span>
</li>

app/views/users/profiles/_transfer.html.erb
<% url = session_transfer_url(user.transfer_id) %>

<fieldset>
  <legend class="gap">
    <%= image_tag "laptop.svg", role: "presentation", size: 36, class: "colorize--black" %>
    <%= image_tag "transfer.svg", role: "presentation", size: 36, class: "colorize--black" %>
    <%= image_tag "mobile-phone.svg", role: "presentation", size: 36, class: "colorize--black" %>
  </legend>


  <div class="flex flex-column gap">
    <% if Current.user != user %>
      <div class="flex align-center gap justify-center">
        <%= image_tag "crown.svg", size: 16, role: "presentation", class: "flex-item-no-shrink colorize--black" %>
        Share to get them back into their account
      </div>
    <% end %>

    <input type="text" class="input" value="<%= url %>" id="session_transfer_url" readonly>

    <div class="flex align-center center gap">
      <%= link_to_zoom_qr_code(url) do %>
        <span class="for-screen-reader">QR code</span>
        <%= image_tag "qr-code.svg", class: "colorize--black" %>
      <% end %>

      <%= button_to_copy_to_clipboard(url) do %>
        <span class="for-screen-reader">Copy URL</span>
        <%= image_tag "copy-paste.svg", class: "flex-item-no-shrink colorize--black" %>
      <% end %>

      <%= web_share_session_button(url, "Your sign-in link", "This is your own private sign-in URL, DO NOT SHARE IT. Use it to sign-in on another device or if you get locked out.") do %>
        <span class="for-screen-reader">Share</span>
        <%= image_tag "share.svg", class: "flex-item-no-shrink colorize--black" %>
      <% end %>
    </div>
  </div>
</fieldset>

app/views/users/profiles/show.html.erb
<% @page_title = @user.name %>

<% content_for :nav do %>
  <div class="flex-item-justify-start">
    <%= link_back %>
  </div>

  <div class="flex-item-justify-end">
    <%= form_with url: session_path, method: :delete, data: { controller: "sessions" } do %>
      <%= hidden_field_tag :push_subscription_endpoint, nil, data: { sessions_target: "pushSubscriptionEndpoint" } %>

      <button class="btn" data-action="sessions#logout:prevent">
        <%= image_tag "logout.svg" %>
        <span class="for-screen-reader">Log out</span>
      </button>
    <% end %>
  </div>
<% end %>

<section class="panel flex flex-column gap" style="view-transition-name: avatar-<%= @user.id %>">
  <%= render partial: "pwa/install_instructions" %>

  <div class="align-center center avatar__form gap" data-controller="upload-preview">
    <%= profile_form_with @user, class:"txt-medium" do |form| %>
      <label class="btn input--file">
        <%= image_tag "camera.svg" %>
        <%= form.file_field :avatar, id: "file", class: "input", accept: "image/*",
            data: { upload_preview_target: "input", action: "upload-preview#previewImage change->form#submit" } %>
        <span class="for-screen-reader">Upload avatar</span>
      </label>
    <% end %>

    <%= profile_form_with @user do |form| %>
      <label class="btn avatar input--file txt-xx-large">
        <%= image_tag fresh_user_avatar_path(@user), role: "presentation", data: { upload_preview_target: "image" } %>
        <%= form.file_field :avatar, id: "file", class: "input", accept: "image/*",
            data: { upload_preview_target: "input", action: "upload-preview#previewImage change->form#submit" } %>
        <span class="for-screen-reader">Avatar</span>
      </label>
    <% end %>

    <% if @user.avatar.attached? %>
      <%= button_to user_avatar_path(@user), method: :delete, class: "btn btn--negative txt-small avatar__delete-btn" do %>
        <%= image_tag "minus.svg" %>
        <span class="for-screen-reader">Delete avatar</span>
      <% end %>
    <% end %>
  </div>

  <%= profile_form_with @user do |form| %>
    <div class="flex flex-column gap">
      <div class="flex align-center gap">
        <%= translation_button(:user_name) %>

        <label class="flex align-center gap flex-item-grow input input--actor">
          <%= form.text_field :name, class: "input txt-large ", autocomplete: "name", placeholder: "Enter your name",
                autofocus: true, required: true,  data: { "1p-ignore": true } %>
          <%= image_tag "person.svg", role: "presentation", size: 24, class: "colorize--black" %>
        </label>
      </div>

      <div class="flex align-center gap">
        <%= translation_button(:email_address) %>

        <label class="flex align-center gap flex-item-grow input input--actor">
          <%= form.email_field :email_address, class: "input txt-large", value: @user.email_address, autocomplete: "username",
                placeholder: "Enter your email address", required: false %>
          <%= image_tag "email.svg", role: "presentation", size: 24, class: "colorize--black" %>
        </label>
      </div>

      <div class="flex align-center gap">
        <%= translation_button(:update_password) %>

        <label class="flex align-center gap flex-item-grow input input--actor">
          <%= form.password_field :password, class: "input txt-large", autocomplete: "new-password", placeholder: "Change password",
                required: false, maxlength: 72 %>
          <%= image_tag "password.svg", role: "presentation", size: 24, class: "colorize--black" %>
        </label>
      </div>

      <div class="flex align-start gap">
        <%= translation_button(:bio) %>

        <label class="flex align--center gap flex-item--grow input input--actor">
          <%= form.text_area :bio, class: "input txt-large", placeholder: "A few words about yourself…", maxlength: 200,
                rows: 3, required: false %>
          <%= image_tag "bio.svg", role: "presentation", size: 24, class: "colorize--black" %>
        </label>
      </div>

      <%= profile_form_submit_button %>
    </div>
  <% end %>

  <div class="margin-block pad-inline pad-block fill-shade border-radius">
    <menu class="flex flex-column gap margin-none pad">
      <%= render partial: "users/profiles/membership", collection: @shared_memberships %>

      <% if @direct_memberships.any? && @shared_memberships.any? %>
        <hr class="separator full-width" style="--border-style: solid">
      <% end %>

      <%= render partial: "users/profiles/membership", collection: @direct_memberships %>
    </menu>
  </div>

  <%= render "users/profiles/transfer", user: @user %>

  <% if Rails.env.development? %>
    <fieldset>
      <legend>
        <%= image_tag "key.svg", role: "presentation", size: 36, class: "colorize--black" %>
      </legend>
      <%= link_to "Push Notifications Dev Mode", user_push_subscriptions_url, class: "btn txt-small center" %>
    </fieldset>
  <% end %>
</section>