config/routes.rb
Rails.application.routes.draw do
  root "welcome#show"

  resource :first_run

  resource :session do
    scope module: "sessions" do
      resources :transfers, only: %i[ show update ]
    end
  end

  resource :account do
    scope module: "accounts" do
      resources :users
      resource :join_code, only: :create
      resource :logo, only: %i[ show destroy ]
    end
  end

  direct :fresh_account_logo do |options|
    route_for :account_logo, v: Current.account&.updated_at&.to_fs(:number)
  end

  get "join/:join_code", to: "users#new", as: :join
  post "join/:join_code", to: "users#create"

  resources :qr_code, only: :show

  resources :users, only: :show do
    scope module: "users" do
      resource :avatar, only: %i[ show destroy ]

      scope defaults: { user_id: "me" } do
        resource :sidebar, only: :show
        resource :profile
        resources :push_subscriptions do
          scope module: "push_subscriptions" do
            resources :test_notifications, only: :create
          end
        end
      end
    end
  end

  namespace :autocompletable do
    resources :users, only: :index
  end

  direct :fresh_user_avatar do |user, options|
    route_for :user_avatar, user, v: user.updated_at.to_fs(:number)
  end

  resources :rooms do
    resources :messages

    scope module: "rooms" do
      resource :refresh, only: :show
      resource :settings, only: :show
      resource :involvement, only: %i[ show update ]
    end

    get "@:message_id", to: "rooms#show", as: :at_message
  end

  namespace :rooms do
    resources :opens
    resources :closeds
    resources :directs
  end

  resources :messages do
    scope module: "messages" do
      resources :boosts
    end
  end

  resources :searches, only: %i[ index create ] do
    delete :clear, on: :collection
  end

  resource :unfurl_link, only: :create

  get "webmanifest"    => "pwa#manifest"
  get "service-worker" => "pwa#service_worker"

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/search.rb
class Search < ApplicationRecord
  belongs_to :user

  after_create :trim_recent_searches

  scope :ordered, -> { order(updated_at: :desc) }

  class << self
    def record(query)
      find_or_create_by(query: query).touch
    end
  end

  private
    def trim_recent_searches
      user.searches.excluding(user.searches.ordered.limit(10)).destroy_all
    end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :set_messages

  def index
    @query = query if query.present?
    @recent_searches = Current.user.searches.ordered
    @return_to_room = last_room_visited
  end

  def create
    Current.user.searches.record(query)
    redirect_to searches_url(q: query)
  end

  def clear
    Current.user.searches.destroy_all
    redirect_to searches_url
  end

  private
    def set_messages
      if query.present?
        @messages = Current.user.reachable_messages.search(query).limit(100)
      else
        @messages = Message.none
      end
    end

    def query
      params[:q]&.gsub(/[^[:word:]]/, " ")
    end
end

app/helpers/searches_helper.rb
module SearchesHelper
  def search_results_tag(&)
    tag.div id: "search-results", class: "messages searches__results", data: {
      controller: "search-results",
      search_results_target: "messages",
      search_results_me_class: "message--me",
      search_results_threaded_class: "message--threaded",
      search_results_mentioned_class: "message--mentioned",
      search_results_formatted_class: "message--formatted"
    }, &
  end
end

app/views/searches/index.html.erb
<% @page_title = "Search" %>
<% @body_class = "sidebar searches" %>

<% content_for :nav do %>
  <% if @query %>
    <div class="searches__query flex align-center gap pad-block-start-half">
      <%= tag.div class: "btn btn--reversed btn--faux align-center gap txt-nowrap" do %>
        <span class="overflow-ellipsis">“<%= @query %>”</span>
        <span class="flex-item-no-shrink"><%= @messages.count %></span>
      <% end %>
    </div>
  <% end %>

  <div class="searches__recents align-center gap pad-block-half overflow-y overflow-hide-scrollbar">
    <% @recent_searches.each do |search| %>
      <%= link_to searches_path(q: search.query), class: "align-center gap room btn txt-nowrap" do %>
        <span class="overflow-ellipsis">“<%= search.query %>”</span>
      <% end %>
    <% end %>

    <% if @recent_searches.any? %>
      <%= button_to clear_searches_url, method: :delete, class: "btn searches__btn",
              data: { turbo_confirm: "Are you sure you want to clear your recent searches?" } do %>
        <%= image_tag "broom.svg", role: "presentation" %>
        <span class="for-screen-reader">Clear recent searches</span>
      <% end %>
    <% end %>
  </div>
<% end %>

<% content_for :sidebar do %>
  <div class="rooms position-relative flex flex-column gap overflow-y overflow-hide-scrollbar">
    <% @recent_searches.each do |search| %>
      <%= link_to searches_path(q: search.query), class: "align-center gap room btn txt-nowrap" do %>
        <span class="overflow-ellipsis">“<%= search.query %>”</span>
      <% end %>
    <% end %>

    <% if @recent_searches.any? %>
      <%= button_to clear_searches_url, method: :delete, class: "btn searches__btn",
              data: { turbo_confirm: "Are you sure you want to clear your recent searches?" } do %>
        <%= image_tag "broom.svg", role: "presentation" %>
        <span class="for-screen-reader">Clear recent searches</span>
      <% end %>
    <% end %>
  </div>
<% end %>

<div id="message-area" class="message-area">
  <div class="message-area--empty min-width center">
    <figure class="center pad">
      <%= image_tag "search.svg", role: "presentation", class: "colorize--black translucent" %>
    </figure>
  </div>

  <%= search_results_tag do %>
    <%= render @messages %>
  <% end %>
</div>

<% content_for :footer do %>
  <div class="composer flex align-end gap">
    <%= link_to room_path(@return_to_room),
            class: "btn flex-item-no-shrink margin-block-end", style: "view-transition-name: input-switcher; --btn-border-radius: 0.5em" do %>
      <%= image_tag "arrow-left.svg", role: "presentation" %>
      <span class="for-screen-reader">Exit search </span>
    <% end %>

    <%= form_with url: searches_path, class: "margin-block flex-item-grow contain flex align-center gap",
          data: { controller: "form", action: "keydown.enter->form#submit:prevent keydown.esc->form#cancel" } do |form| %>
      <div class="composer__input flex align-center flex-item-grow gap full-width input input--actor min-width">
        <%= image_tag "search.svg", size: 20, role: "presentation", class: "composer__input-hint colorize--black", style: "view-transition-name: input-btn;" %>

        <div class="flex-item-grow">
          <%= form.text_field :q, value: params[:q], class: "input", autofocus: true, required: true %>
        </div>

        <%= link_to searches_path, data: { form_target: "cancel" } do %>
          <%= image_tag "remove.svg", role: "presentation", size: 14, class: "colorize--black" %>
        <% end %>

        <%= form.button type: "submit", class: "btn btn--reversed flex-item-no-shrink txt-small", style: "--btn-border-radius: 0.5em" do %>
          <%= image_tag "arrow-up.svg" %>
          <span class="for-screen-reader">Search</span>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>